version: 2
updates:
  # Keep backend npm dependencies up to date
  - package-ecosystem: npm
    directory: /webapp/backend
    schedule:
      interval: weekly
      day: monday
    groups:
      dev-dependencies:
        dependency-type: development
        patterns:
          - "*"
    open-pull-requests-limit: 5

  # Keep GitHub Actions up to date
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
